theme: "alembic"
title: "Starting a blog..."
author: "Shawn Norman"
description: "The purpose of this blog is to document my projects and exploration." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match


# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "example@mail.com"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username
#show_downloads: "true"
#google_analytics: [Your Google Analytics tracking ID]
#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################


header_pages:
#  - resume.html - this must be a file in the root of shawnmichaelnorman.github.io
titles_from_headings:
  strip_title: true
  collections: true
  
collections:
  personal: # collection for personal blog posts
    output: true

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
#remote_theme: pages-themes/hacker@v0.2.0    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  #- jekyll-remote-theme

comments_repo: shawnmichaelnorman/shawnmichaelnorman.github.io

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: 
        - Other
