# Set Theme
#remote_theme: daviddarnes/alembic@main
theme: "minima"

# File excludes
exclude:
- README.md

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jekyll-remote-theme

# Site Settings
title: "My Blog"
author: "Shawn Norman"
description: "The purpose of this blog is to document my projects and exploration with homelab." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
permalink: pretty
#logo: "https://"
# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "example@mail.com"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username
#show_downloads: "true"
#google_analytics: [Your Google Analytics tracking ID]
#rss: rss


comments_repo: shawnmichaelnorman/shawnmichaelnorman.github.io

  
# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true



# Collections settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: 
        - Other
        
kramdown:
  syntax_highlighter_opts:
    disable: true
