source "https://rubygems.org"

gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-mentions"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "jekyll-redirect-from"
gem "jekyll-feed"
gem "jekyll-commonmark"
gem "jekyll-include-cache"
gem "jemoji"
gem "jekyll-remote-theme"
